export const DEALER_CARD_CALLS = [
  'ace.',
  '2.',
  '3.',
  '4.',
  '5.',
  '6.',
  '7.',
  '8.',
  '9.',
  '10.',
  'jack.',
  'queen.',
  'king.',
];

export const HEART_TABLE_PHRASES = [
  ...DEALER_CARD_CALLS,
  ...DEALER_CARD_CALLS.map(card => `Dealer upcard ${card}`),
  ...DEALER_CARD_CALLS.map(card => `Player draws ${card}`),
  ...DEALER_CARD_CALLS.map(card => `Player doubles and draws ${card}`),
  ...Array.from({ length: 28 }, (_, index) => `Total ${index + 4}.`),
  ...Array.from({ length: 10 }, (_, index) => `Total soft ${index + 12}.`),
  'Player spot 1.',
  'Player spot 2.',
  'Split hand 1.',
  'Split hand 2.',
  'Split hand 3.',
  'Split hand 4.',
  'Cards split.',
  'Dealer does not have blackjack.',
  'Dealer shows an ace.',
  'Insurance decision pending.',
  'Even money decision pending.',
  'Betting is open.',
  'Round complete.',
  'Too many. Dealer busts.',
  'Too many. Player busts.',
  ...Array.from({ length: 5 }, (_, index) => `Dealer ${index + 17}.`),
];
